### ISSUE TITLE
Misspelled word “Feagments” in # Matched Fragments in all RESULTS file

### ISSUE THREAD

**Issue by MTShah** [BIRL/SPECTRUM#1]
![bug2](https://user-images.githubusercontent.com/45479518/49273963-7e8a4f80-f498-11e8-864a-241507bc18b1.png)

**Comment by BIRL** [comment]
Fixed, thank you!

**Comment by MTShah** [comment]
The Single mode works okay but the batch mode still has the same mistake.

**Comment by MTShah** [comment]
![bug6](https://user-images.githubusercontent.com/45479518/49287837-c1601d80-f4c0-11e8-85d2-0534d39be3ad.PNG)
