### ISSUE TITLE
Trouble running SPECTRUM

### ISSUE THREAD

**Issue by zrolfs** [BIRL/SPECTRUM#2]
Hello!
I'm getting a crash whenever I try to open the file dialog for the MS Data File. Any suggestions?
![image](https://user-images.githubusercontent.com/16883585/117970852-c7dc5b80-b2ee-11eb-8a47-b84750483656.png)

I get the same error when using the .exe version, but I'm able to select my .mzML file in the file dialog first.
![image](https://user-images.githubusercontent.com/16883585/117977826-d4fd4880-b2f6-11eb-8a0d-707a167d64be.png)

**Comment by BIRL** [comment]
Dear K,

Please assist with the issue.

Best,
Safee
*----*
*Safee Ullah Chaudhary*, Ph.D. | Assistant Professor,
Biomedical Informatics Research Laboratory (BIRL),
Department of Biology, SBA School of Science and Engineering,
Lahore University of Management Sciences (LUMS), Lahore, Pakistan
Voice: +92 42 3560 8352  | Cell: +92 321 4255171 | Fax: +92 42 3560 8317
Email: ***@***.***, ***@***.***
Web: biolabs.lums.edu.pk/BIRL

* *This email message is for the sole use of the intended recipient(s) and
may contain confidential **information. Any unauthorized review, use,
disclosure or distribution is prohibited. *

**Comment by BIRL** [comment]
> Hello!
> I'm getting a crash whenever I try to open the file dialog for the MS Data File. Any suggestions?
> ![image](https://user-images.githubusercontent.com/16883585/117970852-c7dc5b80-b2ee-11eb-8a47-b84750483656.png)
> 
> I get the same error when using the .exe version, but I'm able to select my .mzML file in the file dialog first.
> ![image](https://user-images.githubusercontent.com/16883585/117977826-d4fd4880-b2f6-11eb-8a0d-707a167d64be.png)

Dear Zrolfs,
Thank you for reaching us. SPECTRUM does not support space character in directory or file names, please check if the file path contains special characters or spaces. Additionally, please confirm if the file exists within the folder "Toolbox" or inside its subfolders. SPECTRUM requires Java Runtime Environment 7 or above, please make sure if it is installed. Lastly, please check this "Add to path" link (https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/). For more details, please refer to our user manual and step-by-step user guide at https://github.com/BIRL/SPECTRUM/tree/master/Documentation. For video tutorials, please visit https://www.youtube.com/watch?v=w6gE6uthfaw&list=PLaNVq-kFOn0YH6DpEMlXuxGwz8y7abZfQ. If problem persists, please feel free to contact us. 

We have released SPECTRUM v2.0.0.0, an improved version of SPECTRUM. Please download it from https://github.com/BIRL/SPECTRUM_v2.0.0.0 and use it for data analysis. Kindly let us know if similar problems occur while using SPECTRUM v2.0.0.0.

Thank you for using SPECTRUM, 
Team SPECTRUM

**Comment by zrolfs** [comment]
Hello,
I can no longer reproduce the error, so not sure what was wrong. Thanks for your help!

P.S. I'm checking out SPECTRUM v2 right now. The header might need updating...
![image](https://user-images.githubusercontent.com/16883585/119531537-a301d280-bd49-11eb-9b19-3e2fea002843.png)

**Comment by zrolfs** [comment]
Hmm... New issues now. 
![image](https://user-images.githubusercontent.com/16883585/119533852-e5c4aa00-bd4b-11eb-98de-4f2dc6465a06.png)

**Comment by BIRL** [comment]
> Hmm... New issues now.
> ![image](https://user-images.githubusercontent.com/16883585/119533852-e5c4aa00-bd4b-11eb-98de-4f2dc6465a06.png)

Dear Rolfs,
We have updated the header information, thank you for pointing out.

We have thoroughly tested SPECTRUM v2.0.0.0 using (default parameters, dataset-specific parameters for all file formats in single and batch mode) and have failed to reproduce the error. It would be really helpful for us to identify the associated bug if you can please share the data file, database and input parameters used for search that are leading to this error. 

Thank you for using SPECTRUM,
Team SPECTRUM

**Comment by zrolfs** [comment]
I can share the files I'm using, but I'm getting the same crash when using the default 2.0.0.0 parameters and files that are autofilled when I run the program
![image](https://user-images.githubusercontent.com/16883585/119653382-42c86a80-bdf5-11eb-9609-8b74addfe0bc.png)

(Top-right corner of the GUI should be updated to 2.0.0.0, too).

**Comment by zrolfs** [comment]
Thank you for the Zoom call! I had a great time learning about Spectrum. Turned out all I needed was to install the Bioinformatic Toolbox (can be found in MatLab using the Add-Ins).

**Comment by BIRL** [comment]
Our pleasure Zach! Enjoy the platform!
*----*
*Safee Ullah Chaudhary*, Ph.D. | Assistant Professor,
Biomedical Informatics Research Laboratory (BIRL),
Department of Biology, SBA School of Science and Engineering,
Lahore University of Management Sciences (LUMS), Lahore, Pakistan
Voice: +92 42 3560 8352  | Cell: +92 321 4255171 | Fax: +92 42 3560 8317
Email: ***@***.***, ***@***.***
Web: biolabs.lums.edu.pk/BIRL

* *This email message is for the sole use of the intended recipient(s) and
may contain confidential **information. Any unauthorized review, use,
disclosure or distribution is prohibited. *
